services:
    twig.extension.text:
	class: Twig_Extensions_Extension_Text
	tags:
	    - { name: twig.extension }
    delivery.http.client:
        class:  Guzzle\Http\Client
    delivery.cache:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]
